# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fa42a474f5c34cd2eabae8a8bdf30e0e4b31206c3c541f76e4ea7d7031c0b027427bae37134027a0e5eb7823eaef5905370da8bca533cdfdb18eb008596fe484

test:
  secret_key_base: 74777c30f8fe89177c8cb85b13644945e5a29d239a948caab792a86cae5cd1fbb3520c7098b2899684deaf0ba5fd1bc8f3c9978e668f57081ab04660bc000a31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
